export type SiteContentFieldType = 'text' | 'textarea' | 'image' | 'url';

export interface SiteContentDefault {
  key: string;
  page: string;
  section: string;
  label: string;
  type: SiteContentFieldType;
  value: string;
}

export const SITE_CONTENT_DEFAULTS: SiteContentDefault[] = [
  {
    key: 'global.nav.logoText',
    page: 'global',
    section: 'navbar',
    label: 'Logo Text',
    type: 'text',
    value: 'Nechabest',
  },
  {
    key: 'global.nav.ctaLabel',
    page: 'global',
    section: 'navbar',
    label: 'Navbar CTA Label',
    type: 'text',
    value: 'Book A Tour',
  },
  {
    key: 'global.footer.tagline',
    page: 'global',
    section: 'footer',
    label: 'Footer Tagline',
    type: 'textarea',
    value: 'Together for a Greener Future.',
  },
  {
    key: 'global.footer.emailPrimary',
    page: 'global',
    section: 'footer',
    label: 'Footer Primary Email',
    type: 'text',
    value: 'info@nechabest.com',
  },
  {
    key: 'global.footer.phone',
    page: 'global',
    section: 'footer',
    label: 'Footer Phone',
    type: 'text',
    value: '+256 763 860866',
  },
  {
    key: 'home.hero.title',
    page: 'home',
    section: 'hero',
    label: 'Home Hero Title',
    type: 'textarea',
    value: 'Building a Sustainable Future for People and Nature.',
  },
  {
    key: 'home.hero.subtitle',
    page: 'home',
    section: 'hero',
    label: 'Home Hero Subtitle',
    type: 'textarea',
    value: 'Empowering Ugandan communities through clean water, renewable energy, climate-smart farming, and eco-tourism.',
  },
  {
    key: 'home.hero.image1',
    page: 'home',
    section: 'hero',
    label: 'Home Hero Image 1',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'home.hero.image2',
    page: 'home',
    section: 'hero',
    label: 'Home Hero Image 2',
    type: 'image',
    value: 'https://iili.io/fdClSYg.png',
  },
  {
    key: 'home.about.slide1.title',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 1 Title',
    type: 'text',
    value: 'Who We Are',
  },
  {
    key: 'home.about.slide1.desc',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 1 Description',
    type: 'textarea',
    value: 'Nechabest Sustainable Initiatives is building climate-resilient, environmentally conscious communities through research, innovation, and local empowerment.',
  },
  {
    key: 'home.about.slide1.cta',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 1 CTA Label',
    type: 'text',
    value: 'Learn More About Us →',
  },
  {
    key: 'home.about.slide1.image',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 1 Image',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'home.about.slide2.title',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 2 Title',
    type: 'text',
    value: 'Our Vision',
  },
  {
    key: 'home.about.slide2.desc',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 2 Description',
    type: 'textarea',
    value: 'Bridging the gap between environmental conservation and community development through smart, solar-powered initiatives and local action.',
  },
  {
    key: 'home.about.slide2.cta',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 2 CTA Label',
    type: 'text',
    value: 'Our Vision →',
  },
  {
    key: 'home.about.slide2.image',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 2 Image',
    type: 'image',
    value: 'https://iili.io/fdClSYg.png',
  },
  {
    key: 'home.about.slide3.title',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 3 Title',
    type: 'text',
    value: 'Our Mission',
  },
  {
    key: 'home.about.slide3.desc',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 3 Description',
    type: 'textarea',
    value: 'To create sustainable solutions where people and nature thrive together, ensuring conservation is a lived reality for the people we serve.',
  },
  {
    key: 'home.about.slide3.cta',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 3 CTA Label',
    type: 'text',
    value: 'Our Mission →',
  },
  {
    key: 'home.about.slide3.image',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 3 Image',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'home.focus.heading',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Areas Heading',
    type: 'text',
    value: 'Our Core Focus Areas',
  },
  {
    key: 'home.focus.subtitle',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Areas Subtitle',
    type: 'textarea',
    value: 'Three Pillars of Sustainable Development driving our mission in Uganda.',
  },
  {
    key: 'home.focus.learnMoreLabel',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Areas Learn More Label',
    type: 'text',
    value: 'Learn More',
  },
  {
    key: 'home.focus.area1.title',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 1 Title',
    type: 'text',
    value: 'Water-Energy-Food (WEF) Nexus',
  },
  {
    key: 'home.focus.area1.desc',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 1 Description',
    type: 'textarea',
    value: 'Clean water access, renewable energy solutions, and climate-smart agriculture for sustainable livelihoods.',
  },
  {
    key: 'home.focus.area1.image',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 1 Image',
    type: 'image',
    value: 'https://picsum.photos/seed/water/600/400',
  },
  {
    key: 'home.focus.area2.title',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 2 Title',
    type: 'text',
    value: 'Environmental Conservation',
  },
  {
    key: 'home.focus.area2.desc',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 2 Description',
    type: 'textarea',
    value: 'Tree planting initiatives, watershed protection, and ecosystem restoration for a resilient future.',
  },
  {
    key: 'home.focus.area2.image',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 2 Image',
    type: 'image',
    value: 'https://picsum.photos/seed/energy/600/400',
  },
  {
    key: 'home.focus.area3.title',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 3 Title',
    type: 'text',
    value: 'Green Livelihoods & Innovation',
  },
  {
    key: 'home.focus.area3.desc',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 3 Description',
    type: 'textarea',
    value: 'Consultancy services, youth empowerment programs, and sustainable enterprise development.',
  },
  {
    key: 'home.focus.area3.image',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 3 Image',
    type: 'image',
    value: 'https://picsum.photos/seed/farming/600/400',
  },
  {
    key: 'home.focus.area4.title',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 4 Title',
    type: 'text',
    value: 'Community Health & Well-being',
  },
  {
    key: 'home.focus.area4.desc',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 4 Description',
    type: 'textarea',
    value: 'Improving health outcomes through clean energy and sustainable food systems.',
  },
  {
    key: 'home.focus.area4.image',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 4 Image',
    type: 'image',
    value: 'https://picsum.photos/seed/health/600/400',
  },
  {
    key: 'home.tours.heading',
    page: 'home',
    section: 'tours',
    label: 'Home Tours Heading',
    type: 'text',
    value: 'Explore Uganda',
  },
  {
    key: 'home.tours.subtitle',
    page: 'home',
    section: 'tours',
    label: 'Home Tours Subtitle',
    type: 'textarea',
    value: 'Immerse yourself in the heart of sustainable development through our community-led tours and technical field visits.',
  },
  // ── Impact Section ──────────────────────────────────────────────────────────
  {
    key: 'home.impact.kicker',
    page: 'home',
    section: 'impact',
    label: 'Impact Kicker Label',
    type: 'text',
    value: 'Our Measurable Impact',
  },
  {
    key: 'home.impact.heading',
    page: 'home',
    section: 'impact',
    label: 'Impact Heading',
    type: 'text',
    value: 'Driving Change Across Uganda',
  },
  {
    key: 'home.impact.subtitle',
    page: 'home',
    section: 'impact',
    label: 'Impact Subtitle',
    type: 'textarea',
    value: 'We believe in transparency and results. Every initiative we launch is tracked, measured, and optimized for maximum community benefit.',
  },
  {
    key: 'home.impact.image',
    page: 'home',
    section: 'impact',
    label: 'Impact Image',
    type: 'image',
    value: 'https://iili.io/3oebjFS.jpg',
  },
  // Impact stat cards
  {
    key: 'home.impact.stat1.value',
    page: 'home',
    section: 'impact',
    label: 'Stat 1 Value (Trees Planted)',
    type: 'text',
    value: '10,000+',
  },
  {
    key: 'home.impact.stat1.label',
    page: 'home',
    section: 'impact',
    label: 'Stat 1 Label',
    type: 'text',
    value: 'Trees Planted',
  },
  {
    key: 'home.impact.stat2.value',
    page: 'home',
    section: 'impact',
    label: 'Stat 2 Value (Households Powered)',
    type: 'text',
    value: '1,500+',
  },
  {
    key: 'home.impact.stat2.label',
    page: 'home',
    section: 'impact',
    label: 'Stat 2 Label',
    type: 'text',
    value: 'Households Powered',
  },
  {
    key: 'home.impact.stat3.value',
    page: 'home',
    section: 'impact',
    label: 'Stat 3 Value (Farmers Trained)',
    type: 'text',
    value: '2,000+',
  },
  {
    key: 'home.impact.stat3.label',
    page: 'home',
    section: 'impact',
    label: 'Stat 3 Label',
    type: 'text',
    value: 'Farmers Trained',
  },
  {
    key: 'home.impact.stat4.value',
    page: 'home',
    section: 'impact',
    label: 'Stat 4 Value (Strategic Partners)',
    type: 'text',
    value: '15+',
  },
  {
    key: 'home.impact.stat4.label',
    page: 'home',
    section: 'impact',
    label: 'Stat 4 Label',
    type: 'text',
    value: 'Strategic Partners',
  },
  // Impact quote card
  {
    key: 'home.impact.quote',
    page: 'home',
    section: 'impact',
    label: 'Impact Quote Text',
    type: 'textarea',
    value: 'Sustainability is not just a goal, it\'s our way of life. We are building a legacy for the next generation.',
  },
  {
    key: 'home.impact.quoteRole',
    page: 'home',
    section: 'impact',
    label: 'Impact Quote Role',
    type: 'text',
    value: 'Project Director',
  },
  {
    key: 'home.impact.quoteAuthor',
    page: 'home',
    section: 'impact',
    label: 'Impact Quote Author',
    type: 'text',
    value: 'Nechabest Initiatives',
  },
  // ── Featured Projects Section ────────────────────────────────────────────────
  {
    key: 'home.projects.kicker',
    page: 'home',
    section: 'projects',
    label: 'Projects Kicker Label',
    type: 'text',
    value: 'Innovation & Research',
  },
  {
    key: 'home.projects.heading',
    page: 'home',
    section: 'projects',
    label: 'Projects Heading',
    type: 'text',
    value: 'Featured Projects',
  },
  // Featured (large) project
  {
    key: 'home.projects.featuredTitle',
    page: 'home',
    section: 'projects',
    label: 'Featured Project Title',
    type: 'text',
    value: 'Solar-Powered Water Pumping',
  },
  {
    key: 'home.projects.featuredCategory',
    page: 'home',
    section: 'projects',
    label: 'Featured Project Category',
    type: 'text',
    value: 'WEF Nexus',
  },
  {
    key: 'home.projects.featuredYear',
    page: 'home',
    section: 'projects',
    label: 'Featured Project Year',
    type: 'text',
    value: '2024',
  },
  {
    key: 'home.projects.featuredDesc',
    page: 'home',
    section: 'projects',
    label: 'Featured Project Description',
    type: 'textarea',
    value: 'Implementing renewable energy solutions to provide clean water access to remote communities in Kasese. Our system integrates IoT monitoring for real-time flow data.',
  },
  {
    key: 'home.projects.featuredImage',
    page: 'home',
    section: 'projects',
    label: 'Featured Project Image',
    type: 'image',
    value: 'https://iili.io/f0xoXA7.png',
  },
  // Secondary project 1
  {
    key: 'home.projects.project2Title',
    page: 'home',
    section: 'projects',
    label: 'Project 2 Title',
    type: 'text',
    value: 'Watershed Management',
  },
  {
    key: 'home.projects.project2Category',
    page: 'home',
    section: 'projects',
    label: 'Project 2 Category',
    type: 'text',
    value: 'Conservation',
  },
  {
    key: 'home.projects.project2Image',
    page: 'home',
    section: 'projects',
    label: 'Project 2 Image',
    type: 'image',
    value: 'https://iili.io/fdCAigf.jpg',
  },
  // Secondary project 2
  {
    key: 'home.projects.project3Title',
    page: 'home',
    section: 'projects',
    label: 'Project 3 Title',
    type: 'text',
    value: 'Climate-Smart Farming',
  },
  {
    key: 'home.projects.project3Category',
    page: 'home',
    section: 'projects',
    label: 'Project 3 Category',
    type: 'text',
    value: 'Agriculture',
  },
  {
    key: 'home.projects.project3Image',
    page: 'home',
    section: 'projects',
    label: 'Project 3 Image',
    type: 'image',
    value: 'https://iili.io/fMclk92.jpg',
  },
  // ── Research & Publications Section ─────────────────────────────────────────
  {
    key: 'home.research.heading',
    page: 'home',
    section: 'research',
    label: 'Research Section Heading',
    type: 'text',
    value: 'Latest Research & Publications',
  },
  {
    key: 'home.research.subtitle',
    page: 'home',
    section: 'research',
    label: 'Research Section Subtitle',
    type: 'textarea',
    value: 'Our team actively contributes to the global knowledge base on sustainable development, WEF nexus, and climate adaptation.',
  },
  {
    key: 'home.research.ctaLabel',
    page: 'home',
    section: 'research',
    label: 'Research CTA Label',
    type: 'text',
    value: 'Browse Publication Library',
  },
  // Research item 1
  {
    key: 'home.research.item1.title',
    page: 'home',
    section: 'research',
    label: 'Research Item 1 Title',
    type: 'text',
    value: 'Impact of Micro-Irrigation on Smallholder Yields',
  },
  {
    key: 'home.research.item1.author',
    page: 'home',
    section: 'research',
    label: 'Research Item 1 Author',
    type: 'text',
    value: 'Kenny',
  },
  {
    key: 'home.research.item1.date',
    page: 'home',
    section: 'research',
    label: 'Research Item 1 Date',
    type: 'text',
    value: 'Jan 2024',
  },
  {
    key: 'home.research.item1.tag1',
    page: 'home',
    section: 'research',
    label: 'Research Item 1 Tag 1',
    type: 'text',
    value: 'Irrigation',
  },
  {
    key: 'home.research.item1.tag2',
    page: 'home',
    section: 'research',
    label: 'Research Item 1 Tag 2',
    type: 'text',
    value: 'Economics',
  },
  // Research item 2
  {
    key: 'home.research.item2.title',
    page: 'home',
    section: 'research',
    label: 'Research Item 2 Title',
    type: 'text',
    value: 'Biodiversity Trends in the Rwenzori Foothills',
  },
  {
    key: 'home.research.item2.author',
    page: 'home',
    section: 'research',
    label: 'Research Item 2 Author',
    type: 'text',
    value: 'Rosemary',
  },
  {
    key: 'home.research.item2.date',
    page: 'home',
    section: 'research',
    label: 'Research Item 2 Date',
    type: 'text',
    value: 'Nov 2023',
  },
  {
    key: 'home.research.item2.tag1',
    page: 'home',
    section: 'research',
    label: 'Research Item 2 Tag 1',
    type: 'text',
    value: 'Ecology',
  },
  {
    key: 'home.research.item2.tag2',
    page: 'home',
    section: 'research',
    label: 'Research Item 2 Tag 2',
    type: 'text',
    value: 'GIS',
  },
  {
    key: 'about.hero.title',
    page: 'about',
    section: 'hero',
    label: 'About Hero Title',
    type: 'text',
    value: 'About Nechabest Sustainable Initiatives',
  },
  {
    key: 'about.hero.subtitle',
    page: 'about',
    section: 'hero',
    label: 'About Hero Subtitle',
    type: 'textarea',
    value: 'We combine science and social values to deliver effective solutions for the better management of water, energy, and environment across Africa.',
  },
  {
    key: 'about.hero.image',
    page: 'about',
    section: 'hero',
    label: 'About Hero Image 1',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'about.hero.image2',
    page: 'about',
    section: 'hero',
    label: 'About Hero Image 2',
    type: 'image',
    value: 'https://iili.io/3oebjFS.jpg',
  },
  {
    key: 'blog.hero.title',
    page: 'blog',
    section: 'hero',
    label: 'Blog Hero Title',
    type: 'text',
    value: 'Eco-Insights',
  },
  {
    key: 'blog.hero.subtitle',
    page: 'blog',
    section: 'hero',
    label: 'Blog Hero Subtitle',
    type: 'textarea',
    value: 'Stories, research, and practical guides on sustainable travel and conservation across Africa',
  },
  {
    key: 'blog.hero.image',
    page: 'blog',
    section: 'hero',
    label: 'Blog Hero Image 1',
    type: 'image',
    value: 'https://iili.io/fdClSYg.png',
  },
  {
    key: 'blog.hero.image2',
    page: 'blog',
    section: 'hero',
    label: 'Blog Hero Image 2',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'eco.hero.title',
    page: 'eco-tourism',
    section: 'hero',
    label: 'Eco Tourism Hero Title',
    type: 'text',
    value: 'Eco-Tourism Experiences',
  },
  {
    key: 'eco.hero.subtitle',
    page: 'eco-tourism',
    section: 'hero',
    label: 'Eco Tourism Hero Subtitle',
    type: 'textarea',
    value: "Explore Africa's natural wonders while supporting conservation. Every journey creates lasting impact for communities and the environment.",
  },
  {
    key: 'eco.hero.image',
    page: 'eco-tourism',
    section: 'hero',
    label: 'Eco Tourism Hero Image 1',
    type: 'image',
    value: 'https://iili.io/3ovy0N9.jpg',
  },
  {
    key: 'eco.hero.image2',
    page: 'eco-tourism',
    section: 'hero',
    label: 'Eco Tourism Hero Image 2',
    type: 'image',
    value: 'https://iili.io/F2JCsIf.jpg',
  },
  {
    key: 'contact.hero.title',
    page: 'contact',
    section: 'hero',
    label: 'Contact Hero Title',
    type: 'text',
    value: "Let's Connect",
  },
  {
    key: 'contact.hero.subtitle',
    page: 'contact',
    section: 'hero',
    label: 'Contact Hero Subtitle',
    type: 'textarea',
    value: "Have questions about our tours or partnerships? We'd love to hear from you. Reach out to us anytime.",
  },
  {
    key: 'contact.hero.image',
    page: 'contact',
    section: 'hero',
    label: 'Contact Hero Image 1',
    type: 'image',
    value: 'https://iili.io/fMclk92.jpg',
  },
  {
    key: 'contact.hero.image2',
    page: 'contact',
    section: 'hero',
    label: 'Contact Hero Image 2',
    type: 'image',
    value: 'https://iili.io/fdCAigf.jpg',
  },
  {
    key: 'booking.hero.title',
    page: 'booking',
    section: 'hero',
    label: 'Booking Hero Title',
    type: 'text',
    value: 'Book Your Adventure',
  },
  {
    key: 'booking.hero.image',
    page: 'booking',
    section: 'hero',
    label: 'Booking Hero Image 1',
    type: 'image',
    value: 'https://iili.io/FvzmxwP.jpg',
  },
  {
    key: 'booking.hero.image2',
    page: 'booking',
    section: 'hero',
    label: 'Booking Hero Image 2',
    type: 'image',
    value: 'https://iili.io/FCfM08X.jpg',
  },
];
