export type SiteContentFieldType = 'text' | 'textarea' | 'image' | 'url';

export interface SiteContentDefault {
  key: string;
  page: string;
  section: string;
  label: string;
  type: SiteContentFieldType;
  value: string;
}

export const SITE_CONTENT_DEFAULTS: SiteContentDefault[] = [
  {
    key: 'global.nav.logoText',
    page: 'global',
    section: 'navbar',
    label: 'Logo Text',
    type: 'text',
    value: 'Nechabest',
  },
  {
    key: 'global.nav.ctaLabel',
    page: 'global',
    section: 'navbar',
    label: 'Navbar CTA Label',
    type: 'text',
    value: 'Book A Tour',
  },
  {
    key: 'global.footer.tagline',
    page: 'global',
    section: 'footer',
    label: 'Footer Tagline',
    type: 'textarea',
    value: 'Together for a Greener Future.',
  },
  {
    key: 'global.footer.emailPrimary',
    page: 'global',
    section: 'footer',
    label: 'Footer Primary Email',
    type: 'text',
    value: 'info@nechabest.com',
  },
  {
    key: 'global.footer.phone',
    page: 'global',
    section: 'footer',
    label: 'Footer Phone',
    type: 'text',
    value: '+256 763 860866',
  },
  {
    key: 'home.hero.title',
    page: 'home',
    section: 'hero',
    label: 'Home Hero Title',
    type: 'textarea',
    value: 'Building a Sustainable Future for People and Nature.',
  },
  {
    key: 'home.hero.subtitle',
    page: 'home',
    section: 'hero',
    label: 'Home Hero Subtitle',
    type: 'textarea',
    value: 'Empowering Ugandan communities through clean water, renewable energy, climate-smart farming, and eco-tourism.',
  },
  {
    key: 'home.hero.image1',
    page: 'home',
    section: 'hero',
    label: 'Home Hero Image 1',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'home.hero.image2',
    page: 'home',
    section: 'hero',
    label: 'Home Hero Image 2',
    type: 'image',
    value: 'https://iili.io/fdClSYg.png',
  },
  {
    key: 'home.about.slide1.title',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 1 Title',
    type: 'text',
    value: 'Who We Are',
  },
  {
    key: 'home.about.slide1.desc',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 1 Description',
    type: 'textarea',
    value: 'Nechabest Sustainable Initiatives is building climate-resilient, environmentally conscious communities through research, innovation, and local empowerment.',
  },
  {
    key: 'home.about.slide1.cta',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 1 CTA Label',
    type: 'text',
    value: 'Learn More About Us →',
  },
  {
    key: 'home.about.slide1.image',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 1 Image',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'home.about.slide2.title',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 2 Title',
    type: 'text',
    value: 'Our Vision',
  },
  {
    key: 'home.about.slide2.desc',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 2 Description',
    type: 'textarea',
    value: 'Bridging the gap between environmental conservation and community development through smart, solar-powered initiatives and local action.',
  },
  {
    key: 'home.about.slide2.cta',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 2 CTA Label',
    type: 'text',
    value: 'Our Vision →',
  },
  {
    key: 'home.about.slide2.image',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 2 Image',
    type: 'image',
    value: 'https://iili.io/fdClSYg.png',
  },
  {
    key: 'home.about.slide3.title',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 3 Title',
    type: 'text',
    value: 'Our Mission',
  },
  {
    key: 'home.about.slide3.desc',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 3 Description',
    type: 'textarea',
    value: 'To create sustainable solutions where people and nature thrive together, ensuring conservation is a lived reality for the people we serve.',
  },
  {
    key: 'home.about.slide3.cta',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 3 CTA Label',
    type: 'text',
    value: 'Our Mission →',
  },
  {
    key: 'home.about.slide3.image',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 3 Image',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'home.focus.heading',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Areas Heading',
    type: 'text',
    value: 'Our Core Focus Areas',
  },
  {
    key: 'home.focus.subtitle',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Areas Subtitle',
    type: 'textarea',
    value: 'Three Pillars of Sustainable Development driving our mission in Uganda.',
  },
  {
    key: 'home.focus.learnMoreLabel',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Areas Learn More Label',
    type: 'text',
    value: 'Learn More',
  },
  {
    key: 'home.focus.area1.title',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 1 Title',
    type: 'text',
    value: 'Water-Energy-Food (WEF) Nexus',
  },
  {
    key: 'home.focus.area1.desc',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 1 Description',
    type: 'textarea',
    value: 'Clean water access, renewable energy solutions, and climate-smart agriculture for sustainable livelihoods.',
  },
  {
    key: 'home.focus.area1.image',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 1 Image',
    type: 'image',
    value: 'https://picsum.photos/seed/water/600/400',
  },
  {
    key: 'home.focus.area2.title',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 2 Title',
    type: 'text',
    value: 'Environmental Conservation',
  },
  {
    key: 'home.focus.area2.desc',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 2 Description',
    type: 'textarea',
    value: 'Tree planting initiatives, watershed protection, and ecosystem restoration for a resilient future.',
  },
  {
    key: 'home.focus.area2.image',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 2 Image',
    type: 'image',
    value: 'https://picsum.photos/seed/energy/600/400',
  },
  {
    key: 'home.focus.area3.title',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 3 Title',
    type: 'text',
    value: 'Green Livelihoods & Innovation',
  },
  {
    key: 'home.focus.area3.desc',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 3 Description',
    type: 'textarea',
    value: 'Consultancy services, youth empowerment programs, and sustainable enterprise development.',
  },
  {
    key: 'home.focus.area3.image',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 3 Image',
    type: 'image',
    value: 'https://picsum.photos/seed/farming/600/400',
  },
  {
    key: 'home.focus.area4.title',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 4 Title',
    type: 'text',
    value: 'Community Health & Well-being',
  },
  {
    key: 'home.focus.area4.desc',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 4 Description',
    type: 'textarea',
    value: 'Improving health outcomes through clean energy and sustainable food systems.',
  },
  {
    key: 'home.focus.area4.image',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 4 Image',
    type: 'image',
    value: 'https://picsum.photos/seed/health/600/400',
  },
  {
    key: 'home.tours.heading',
    page: 'home',
    section: 'tours',
    label: 'Home Tours Heading',
    type: 'text',
    value: 'Explore Uganda',
  },
  {
    key: 'home.tours.subtitle',
    page: 'home',
    section: 'tours',
    label: 'Home Tours Subtitle',
    type: 'textarea',
    value: 'Immerse yourself in the heart of sustainable development through our community-led tours and technical field visits.',
  },
  {
    key: 'home.impact.heading',
    page: 'home',
    section: 'impact',
    label: 'Home Impact Heading',
    type: 'text',
    value: 'Driving Change Across Uganda',
  },
  {
    key: 'home.impact.image',
    page: 'home',
    section: 'impact',
    label: 'Home Impact Image',
    type: 'image',
    value: 'https://picsum.photos/seed/impact-uganda/1000/1250',
  },
  {
    key: 'home.projects.heading',
    page: 'home',
    section: 'projects',
    label: 'Home Projects Heading',
    type: 'text',
    value: 'Featured Projects',
  },
  {
    key: 'home.projects.featuredTitle',
    page: 'home',
    section: 'projects',
    label: 'Home Featured Project Title',
    type: 'text',
    value: 'Solar-Powered Water Pumping',
  },
  {
    key: 'about.hero.title',
    page: 'about',
    section: 'hero',
    label: 'About Hero Title',
    type: 'text',
    value: 'About Nechabest Sustainable Initiatives',
  },
  {
    key: 'about.hero.subtitle',
    page: 'about',
    section: 'hero',
    label: 'About Hero Subtitle',
    type: 'textarea',
    value: 'We combine science and social values to deliver effective solutions for the better management of water, energy, and environment across Africa.',
  },
  {
    key: 'about.hero.image',
    page: 'about',
    section: 'hero',
    label: 'About Hero Image',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'blog.hero.title',
    page: 'blog',
    section: 'hero',
    label: 'Blog Hero Title',
    type: 'text',
    value: 'Eco-Insights',
  },
  {
    key: 'blog.hero.subtitle',
    page: 'blog',
    section: 'hero',
    label: 'Blog Hero Subtitle',
    type: 'textarea',
    value: 'Stories, research, and practical guides on sustainable travel and conservation across Africa',
  },
  {
    key: 'blog.hero.image',
    page: 'blog',
    section: 'hero',
    label: 'Blog Hero Image',
    type: 'image',
    value: 'https://picsum.photos/seed/blog-hero/2560/1440',
  },
  {
    key: 'eco.hero.title',
    page: 'eco-tourism',
    section: 'hero',
    label: 'Eco Tourism Hero Title',
    type: 'text',
    value: 'Eco-Tourism Experiences',
  },
  {
    key: 'eco.hero.subtitle',
    page: 'eco-tourism',
    section: 'hero',
    label: 'Eco Tourism Hero Subtitle',
    type: 'textarea',
    value: "Explore Africa's natural wonders while supporting conservation. Every journey creates lasting impact for communities and the environment.",
  },
  {
    key: 'eco.hero.image',
    page: 'eco-tourism',
    section: 'hero',
    label: 'Eco Tourism Hero Image',
    type: 'image',
    value: 'https://picsum.photos/seed/eco-tourism-hero/2560/1440',
  },
  {
    key: 'contact.hero.title',
    page: 'contact',
    section: 'hero',
    label: 'Contact Hero Title',
    type: 'text',
    value: "Let's Connect",
  },
  {
    key: 'contact.hero.subtitle',
    page: 'contact',
    section: 'hero',
    label: 'Contact Hero Subtitle',
    type: 'textarea',
    value: "Have questions about our tours or partnerships? We'd love to hear from you. Reach out to us anytime.",
  },
  {
    key: 'contact.hero.image',
    page: 'contact',
    section: 'hero',
    label: 'Contact Hero Image',
    type: 'image',
    value: 'https://picsum.photos/seed/contact-hero/2560/1440',
  },
  {
    key: 'booking.hero.title',
    page: 'booking',
    section: 'hero',
    label: 'Booking Hero Title',
    type: 'text',
    value: 'Book Your Adventure',
  },
];
