export type SiteContentFieldType = 'text' | 'textarea' | 'image' | 'url';

export interface SiteContentDefault {
  key: string;
  page: string;
  section: string;
  label: string;
  type: SiteContentFieldType;
  value: string;
}

export const SITE_CONTENT_DEFAULTS: SiteContentDefault[] = [
  {
    key: 'global.nav.logoText',
    page: 'global',
    section: 'navbar',
    label: 'Logo Text',
    type: 'text',
    value: 'Nechabest',
  },
  {
    key: 'global.nav.ctaLabel',
    page: 'global',
    section: 'navbar',
    label: 'Navbar CTA Label',
    type: 'text',
    value: 'Book A Tour',
  },
  {
    key: 'global.footer.tagline',
    page: 'global',
    section: 'footer',
    label: 'Footer Tagline',
    type: 'textarea',
    value: 'Your Gateway to Unforgettable Adventures.',
  },
  {
    key: 'global.footer.emailPrimary',
    page: 'global',
    section: 'footer',
    label: 'Footer Primary Email',
    type: 'text',
    value: 'info@nechabest.com',
  },
  {
    key: 'global.footer.phone',
    page: 'global',
    section: 'footer',
    label: 'Footer Phone',
    type: 'text',
    value: '+256 763 860866',
  },
  {
    key: 'home.hero.title',
    page: 'home',
    section: 'hero',
    label: 'Home Hero Title',
    type: 'textarea',
    value: 'Unforgettable Adventures Await.',
  },
  {
    key: 'home.hero.subtitle',
    page: 'home',
    section: 'hero',
    label: 'Home Hero Subtitle',
    type: 'textarea',
    value: 'Discover Uganda with Nechabest Sustainable Adventures. Gorilla trekking, wildlife safaris, mountain hiking, and cultural immersion.',
  },
  {
    key: 'home.hero.image1',
    page: 'home',
    section: 'hero',
    label: 'Home Hero Image 1',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'home.hero.image2',
    page: 'home',
    section: 'hero',
    label: 'Home Hero Image 2',
    type: 'image',
    value: 'https://iili.io/fdClSYg.png',
  },
  {
    key: 'home.about.slide1.title',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 1 Title',
    type: 'text',
    value: 'Who We Are',
  },
  {
    key: 'home.about.slide1.desc',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 1 Description',
    type: 'textarea',
    value: 'Nechabest Sustainable Adventures is Uganda\'s premier adventure tour operator, specializing in gorilla trekking, wildlife safaris, and cultural experiences across East Africa.',
  },
  {
    key: 'home.about.slide1.cta',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 1 CTA Label',
    type: 'text',
    value: 'Learn More About Us →',
  },
  {
    key: 'home.about.slide1.image',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 1 Image',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'home.about.slide2.title',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 2 Title',
    type: 'text',
    value: 'Our Vision',
  },
  {
    key: 'home.about.slide2.desc',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 2 Description',
    type: 'textarea',
    value: 'To be East Africa\'s most trusted adventure company, creating extraordinary experiences that connect travelers with the wild beauty of Uganda and beyond.',
  },
  {
    key: 'home.about.slide2.cta',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 2 CTA Label',
    type: 'text',
    value: 'Our Vision →',
  },
  {
    key: 'home.about.slide2.image',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 2 Image',
    type: 'image',
    value: 'https://iili.io/fdClSYg.png',
  },
  {
    key: 'home.about.slide3.title',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 3 Title',
    type: 'text',
    value: 'Our Mission',
  },
  {
    key: 'home.about.slide3.desc',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 3 Description',
    type: 'textarea',
    value: 'To deliver safe, immersive, and unforgettable adventure experiences while supporting local communities and preserving Uganda\'s natural heritage for future generations.',
  },
  {
    key: 'home.about.slide3.cta',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 3 CTA Label',
    type: 'text',
    value: 'Our Mission →',
  },
  {
    key: 'home.about.slide3.image',
    page: 'home',
    section: 'about-slideshow',
    label: 'About Slide 3 Image',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'home.focus.heading',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Areas Heading',
    type: 'text',
    value: 'Why Travel With Us',
  },
  {
    key: 'home.focus.subtitle',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Areas Subtitle',
    type: 'textarea',
    value: 'Three reasons adventurers choose Nechabest Sustainable Adventures for their Uganda experience.',
  },
  {
    key: 'home.focus.learnMoreLabel',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Areas Learn More Label',
    type: 'text',
    value: 'Learn More',
  },
  {
    key: 'home.focus.area1.title',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 1 Title',
    type: 'text',
    value: 'Expert-Guided Safaris',
  },
  {
    key: 'home.focus.area1.desc',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 1 Description',
    type: 'textarea',
    value: 'Our certified guides have decades of experience navigating Uganda\'s national parks, ensuring safe and extraordinary wildlife encounters.',
  },
  {
    key: 'home.focus.area1.image',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 1 Image',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'home.focus.area2.title',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 2 Title',
    type: 'text',
    value: 'Unique Destinations',
  },
  {
    key: 'home.focus.area2.desc',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 2 Description',
    type: 'textarea',
    value: 'From Bwindi Impenetrable Forest to Queen Elizabeth National Park, we take you to Uganda\'s most breathtaking and exclusive locations.',
  },
  {
    key: 'home.focus.area2.image',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 2 Image',
    type: 'image',
    value: 'https://iili.io/fdClSYg.png',
  },
  {
    key: 'home.focus.area3.title',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 3 Title',
    type: 'text',
    value: 'Tailored Experiences',
  },
  {
    key: 'home.focus.area3.desc',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 3 Description',
    type: 'textarea',
    value: 'Every adventure is crafted to your preferences — from luxury gorilla trekking to budget-friendly group safaris and honeymoon packages.',
  },
  {
    key: 'home.focus.area3.image',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 3 Image',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'home.focus.area4.title',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 4 Title',
    type: 'text',
    value: 'Community Impact',
  },
  {
    key: 'home.focus.area4.desc',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 4 Description',
    type: 'textarea',
    value: 'Every booking directly supports local communities through employment, education initiatives, and sustainable tourism practices.',
  },
  {
    key: 'home.focus.area4.image',
    page: 'home',
    section: 'focus-areas',
    label: 'Focus Area 4 Image',
    type: 'image',
    value: 'https://iili.io/fdClSYg.png',
  },
  {
    key: 'home.tours.heading',
    page: 'home',
    section: 'tours',
    label: 'Home Tours Heading',
    type: 'text',
    value: 'Explore Uganda',
  },
  {
    key: 'home.tours.subtitle',
    page: 'home',
    section: 'tours',
    label: 'Home Tours Subtitle',
    type: 'textarea',
    value: 'Handpicked adventures across Uganda\'s most stunning landscapes. Gorilla trekking, wildlife safaris, and cultural immersions.',
  },
  {
    key: 'home.impact.kicker',
    page: 'home',
    section: 'impact',
    label: 'Impact Kicker Label',
    type: 'text',
    value: 'Our Track Record',
  },
  {
    key: 'home.impact.heading',
    page: 'home',
    section: 'impact',
    label: 'Impact Heading',
    type: 'text',
    value: 'Adventures Delivered',
  },
  {
    key: 'home.impact.subtitle',
    page: 'home',
    section: 'impact',
    label: 'Impact Subtitle',
    type: 'textarea',
    value: 'Numbers that reflect our commitment to delivering extraordinary adventure experiences across Uganda.',
  },
  {
    key: 'home.impact.image',
    page: 'home',
    section: 'impact',
    label: 'Impact Image',
    type: 'image',
    value: 'https://iili.io/3oebjFS.jpg',
  },
  {
    key: 'home.impact.stat1.value',
    page: 'home',
    section: 'impact',
    label: 'Stat 1 Value',
    type: 'text',
    value: '2,500+',
  },
  {
    key: 'home.impact.stat1.label',
    page: 'home',
    section: 'impact',
    label: 'Stat 1 Label',
    type: 'text',
    value: 'Happy Travelers',
  },
  {
    key: 'home.impact.stat2.value',
    page: 'home',
    section: 'impact',
    label: 'Stat 2 Value',
    type: 'text',
    value: '15+',
  },
  {
    key: 'home.impact.stat2.label',
    page: 'home',
    section: 'impact',
    label: 'Stat 2 Label',
    type: 'text',
    value: 'Tour Packages',
  },
  {
    key: 'home.impact.stat3.value',
    page: 'home',
    section: 'impact',
    label: 'Stat 3 Value',
    type: 'text',
    value: '10+',
  },
  {
    key: 'home.impact.stat3.label',
    page: 'home',
    section: 'impact',
    label: 'Stat 3 Label',
    type: 'text',
    value: 'Years Experience',
  },
  {
    key: 'home.impact.stat4.value',
    page: 'home',
    section: 'impact',
    label: 'Stat 4 Value',
    type: 'text',
    value: '4.9',
  },
  {
    key: 'home.impact.stat4.label',
    page: 'home',
    section: 'impact',
    label: 'Stat 4 Label',
    type: 'text',
    value: 'Average Rating',
  },
  {
    key: 'home.impact.quote',
    page: 'home',
    section: 'impact',
    label: 'Impact Quote Text',
    type: 'textarea',
    value: 'The gorilla trekking experience was absolutely life-changing. Our guide was incredible, and every detail was taken care of.',
  },
  {
    key: 'home.impact.quoteRole',
    page: 'home',
    section: 'impact',
    label: 'Impact Quote Role',
    type: 'text',
    value: 'Happy Traveler',
  },
  {
    key: 'home.impact.quoteAuthor',
    page: 'home',
    section: 'impact',
    label: 'Impact Quote Author',
    type: 'text',
    value: 'Nechabest Sustainable Adventures',
  },
  {
    key: 'home.projects.kicker',
    page: 'home',
    section: 'projects',
    label: 'Projects Kicker Label',
    type: 'text',
    value: 'Featured Adventures',
  },
  {
    key: 'home.projects.heading',
    page: 'home',
    section: 'projects',
    label: 'Projects Heading',
    type: 'text',
    value: 'Popular Tour Packages',
  },
  {
    key: 'home.projects.featuredTitle',
    page: 'home',
    section: 'projects',
    label: 'Featured Project Title',
    type: 'text',
    value: 'Gorilla Trekking Express',
  },
  {
    key: 'home.projects.featuredCategory',
    page: 'home',
    section: 'projects',
    label: 'Featured Project Category',
    type: 'text',
    value: 'Wildlife Safari',
  },
  {
    key: 'home.projects.featuredYear',
    page: 'home',
    section: 'projects',
    label: 'Featured Project Year',
    type: 'text',
    value: '3 Days',
  },
  {
    key: 'home.projects.featuredDesc',
    page: 'home',
    section: 'projects',
    label: 'Featured Project Description',
    type: 'textarea',
    value: 'An intimate 3-day gorilla trekking experience in Bwindi Impenetrable Forest. Track mountain gorillas in their natural habitat with expert guides.',
  },
  {
    key: 'home.projects.featuredImage',
    page: 'home',
    section: 'projects',
    label: 'Featured Project Image',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'home.projects.project2Title',
    page: 'home',
    section: 'projects',
    label: 'Project 2 Title',
    type: 'text',
    value: 'Uganda Adventure Package',
  },
  {
    key: 'home.projects.project2Category',
    page: 'home',
    section: 'projects',
    label: 'Project 2 Category',
    type: 'text',
    value: 'Multi-Day Safari',
  },
  {
    key: 'home.projects.project2Image',
    page: 'home',
    section: 'projects',
    label: 'Project 2 Image',
    type: 'image',
    value: 'https://iili.io/fdClSYg.png',
  },
  {
    key: 'home.projects.project3Title',
    page: 'home',
    section: 'projects',
    label: 'Project 3 Title',
    type: 'text',
    value: 'Luxury Gorilla & Fly-In Safari',
  },
  {
    key: 'home.projects.project3Category',
    page: 'home',
    section: 'projects',
    label: 'Project 3 Category',
    type: 'text',
    value: 'Luxury Safari',
  },
  {
    key: 'home.projects.project3Image',
    page: 'home',
    section: 'projects',
    label: 'Project 3 Image',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'home.research.heading',
    page: 'home',
    section: 'research',
    label: 'Research Section Heading',
    type: 'text',
    value: 'Travel Stories & Tips',
  },
  {
    key: 'home.research.subtitle',
    page: 'home',
    section: 'research',
    label: 'Research Section Subtitle',
    type: 'textarea',
    value: 'Insider guides, travel tips, and stories from the field to help you plan your perfect Uganda adventure.',
  },
  {
    key: 'home.research.ctaLabel',
    page: 'home',
    section: 'research',
    label: 'Research CTA Label',
    type: 'text',
    value: 'Read Our Blog',
  },
  {
    key: 'home.research.item1.title',
    page: 'home',
    section: 'research',
    label: 'Research Item 1 Title',
    type: 'text',
    value: 'Ultimate Guide to Gorilla Trekking in Uganda',
  },
  {
    key: 'home.research.item1.author',
    page: 'home',
    section: 'research',
    label: 'Research Item 1 Author',
    type: 'text',
    value: 'Nechabest Team',
  },
  {
    key: 'home.research.item1.date',
    page: 'home',
    section: 'research',
    label: 'Research Item 1 Date',
    type: 'text',
    value: 'Jan 2024',
  },
  {
    key: 'home.research.item1.tag1',
    page: 'home',
    section: 'research',
    label: 'Research Item 1 Tag 1',
    type: 'text',
    value: 'Gorilla Trekking',
  },
  {
    key: 'home.research.item1.tag2',
    page: 'home',
    section: 'research',
    label: 'Research Item 1 Tag 2',
    type: 'text',
    value: 'Travel Tips',
  },
  {
    key: 'home.research.item2.title',
    page: 'home',
    section: 'research',
    label: 'Research Item 2 Title',
    type: 'text',
    value: 'Best Time to Visit Queen Elizabeth National Park',
  },
  {
    key: 'home.research.item2.author',
    page: 'home',
    section: 'research',
    label: 'Research Item 2 Author',
    type: 'text',
    value: 'Nechabest Team',
  },
  {
    key: 'home.research.item2.date',
    page: 'home',
    section: 'research',
    label: 'Research Item 2 Date',
    type: 'text',
    value: 'Nov 2023',
  },
  {
    key: 'home.research.item2.tag1',
    page: 'home',
    section: 'research',
    label: 'Research Item 2 Tag 1',
    type: 'text',
    value: 'Wildlife Safari',
  },
  {
    key: 'home.research.item2.tag2',
    page: 'home',
    section: 'research',
    label: 'Research Item 2 Tag 2',
    type: 'text',
    value: 'Destination Guide',
  },
  {
    key: 'about.hero.title',
    page: 'about',
    section: 'hero',
    label: 'About Hero Title',
    type: 'text',
    value: 'About Nechabest Sustainable Adventures',
  },
  {
    key: 'about.hero.subtitle',
    page: 'about',
    section: 'hero',
    label: 'About Hero Subtitle',
    type: 'textarea',
    value: 'Uganda\'s premier adventure tour operator. We craft extraordinary gorilla trekking, wildlife safari, and cultural experiences across East Africa.',
  },
  {
    key: 'about.hero.image',
    page: 'about',
    section: 'hero',
    label: 'About Hero Image 1',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'about.hero.image2',
    page: 'about',
    section: 'hero',
    label: 'About Hero Image 2',
    type: 'image',
    value: 'https://iili.io/3oebjFS.jpg',
  },
  {
    key: 'blog.hero.title',
    page: 'blog',
    section: 'hero',
    label: 'Blog Hero Title',
    type: 'text',
    value: 'Adventure Insights',
  },
  {
    key: 'blog.hero.subtitle',
    page: 'blog',
    section: 'hero',
    label: 'Blog Hero Subtitle',
    type: 'textarea',
    value: 'Travel stories, insider tips, and expert guides for planning your Uganda adventure.',
  },
  {
    key: 'blog.hero.image',
    page: 'blog',
    section: 'hero',
    label: 'Blog Hero Image 1',
    type: 'image',
    value: 'https://iili.io/fdClSYg.png',
  },
  {
    key: 'blog.hero.image2',
    page: 'blog',
    section: 'hero',
    label: 'Blog Hero Image 2',
    type: 'image',
    value: 'https://iili.io/fdC0KF9.jpg',
  },
  {
    key: 'adventures.hero.title',
    page: 'adventures',
    section: 'hero',
    label: 'Adventures Hero Title',
    type: 'text',
    value: 'Adventure Experiences',
  },
  {
    key: 'adventures.hero.subtitle',
    page: 'adventures',
    section: 'hero',
    label: 'Adventures Hero Subtitle',
    type: 'textarea',
    value: 'Explore Uganda\'s most breathtaking landscapes. Gorilla trekking, wildlife safaris, mountain hiking, and cultural immersion.',
  },
  {
    key: 'adventures.hero.image',
    page: 'adventures',
    section: 'hero',
    label: 'Adventures Hero Image 1',
    type: 'image',
    value: 'https://iili.io/3ovy0N9.jpg',
  },
  {
    key: 'adventures.hero.image2',
    page: 'adventures',
    section: 'hero',
    label: 'Adventures Hero Image 2',
    type: 'image',
    value: 'https://iili.io/F2JCsIf.jpg',
  },
  {
    key: 'contact.hero.title',
    page: 'contact',
    section: 'hero',
    label: 'Contact Hero Title',
    type: 'text',
    value: "Let's Connect",
  },
  {
    key: 'contact.hero.subtitle',
    page: 'contact',
    section: 'hero',
    label: 'Contact Hero Subtitle',
    type: 'textarea',
    value: "Have questions about our tours or partnerships? We'd love to hear from you. Reach out to us anytime.",
  },
  {
    key: 'contact.hero.image',
    page: 'contact',
    section: 'hero',
    label: 'Contact Hero Image 1',
    type: 'image',
    value: 'https://iili.io/fMclk92.jpg',
  },
  {
    key: 'contact.hero.image2',
    page: 'contact',
    section: 'hero',
    label: 'Contact Hero Image 2',
    type: 'image',
    value: 'https://iili.io/fdCAigf.jpg',
  },
  {
    key: 'booking.hero.title',
    page: 'booking',
    section: 'hero',
    label: 'Booking Hero Title',
    type: 'text',
    value: 'Book Your Adventure',
  },
  {
    key: 'booking.hero.image',
    page: 'booking',
    section: 'hero',
    label: 'Booking Hero Image 1',
    type: 'image',
    value: 'https://iili.io/FvzmxwP.jpg',
  },
  {
    key: 'booking.hero.image2',
    page: 'booking',
    section: 'hero',
    label: 'Booking Hero Image 2',
    type: 'image',
    value: 'https://iili.io/FCfM08X.jpg',
  },
];
